### ISSUE TITLE
Docs copy-paste mistake with _.unzip function

### ISSUE THREAD

**Issue by vaverix** [jashkenas/underscore#2441]
There is a misinformation about "unzip" function in the docs. Seems like a example was copied from "zip" description and someone forgot to change this.

Now it is:
`_.unzip([['moe', 'larry', 'curly'], [30, 40, 50], [true, false, false]])`
`=> ["moe", 30, true], ["larry", 40, false], ["curly", 50, false]`

Should be (The opposite of "zip" function):
`_.unzip([["moe", 30, true], ["larry", 40, false], ["curly", 50, false]])`
`=> ['moe', 'larry', 'curly'], [30, 40, 50], [true, false, false]`

Cheers!

**Comment by akre54** [comment]
Feel free to open a pull!

**Comment by vaverix** [comment]
Done!

**Comment by danjger** [comment]
The Docs page is still showing the incorrect example for unzip
Should I pull and fix?

**Comment by akre54** [comment]
Sorry about that, it was pulled into master but not gh-pages. It should be live on underscorejs.org now.

**Comment by danjger** [comment]
checks out great, thanks.
